### PR TITLE
Add new [timeTo]DOMContentFlushed custom-metric file/JS snippet

### PR DESCRIPTION
**Pull request by stephendonner**
This, I believe (per https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/custom-metrics#TOC-Specifying-custom-metrics-statically-private-instances-: and the example in https://github.com/WPO-Foundation/webpagetest/blob/06bc77e52af1060d4731d18cce6c3a798d0930bb/www/settings/custom_metrics/scriptTagCount.js.sample), will return the value of ```window.performance.timing.timeToDOMContentFlushed``` as ```domContentFlushed```

This is so we’re able to start using timeToDOMContentFlushed in our Alexa topsites tests.  It landed here: https://github.com/WPO-Foundation/wptagent/pull/181

@jbuck @soulgalore @philbooth r?

### CODE REVIEW

**Review by philbooth — APPROVED** [review]
LGTM

**Review by jbuck — APPROVED** [review]

**Comment by stephendonner** [comment]
Per Patrick Meenan, once we pull and update with version 18.09, we shouldn't need this patch (yay!), as the metrics will be baked in automagically.

**Comment by stephendonner** [comment]
Going to take this, after all, while https://github.com/WPO-Foundation/webpagetest/issues/1198 gets sorted out.

**Comment by stephendonner** [comment]
And here's a satisfying image of it working, server-side, at https://wpt-api.stage.mozaws.net/result/181002_YE_5D/?f=json

screen shot 2018-10-02 at 12 02 58 am

**Pull request merged**
